### ISSUE TITLE
un-normal read value using ubutun 20 x64 with libfwlib32-linux-x64.so.1.0.5

### ISSUE THREAD

**Issue by qmzeng** [strangesast/fwlib#10]
I build my app in ubuntu 20 x64 with ibfwlib32-linux-x64.so.1.0.5, some of the read result is extremely huge and i think it is un-normal, as below:

connected to machine at 10.10.235.161:8193  
machine id: 3c7b5d01-da91ac76-5e31c389-4b92c469, handler: 32769  
running status 0  
emergency 0  
alarm 1  
running program no: 0, main program no: 12  
spindle speed: 93962030282464  
current feed rate = 93962030282464

the spindle speed and feed rate seems not right

Do I miss some options in linux x64?

My gcc build is:

`gcc -L./lib -Wl,-rpath . ./src/reader.c ./src/fanuc.c -lfwlib32 -lm -lpthread -o reader`

**Comment by strangesast** [comment]
I've had fewer issues with the 32bit version (libfwlib32-linux-x86.so.1.0.0 or libfwlib32-linux-x86.so.1.0.5) so I would recommend using it if you can help it.  But that's a pain if you're trying to interface with another 64bit library/process (Python etc).

This library incorrectly assumes a consistent "long" length across platforms.  Longs are treated as 32bit integers even in the 64bit fwlib shared library.

You'll have to cast longs to int32_t and unsigned longs to uint32_T (as in [the example script](https://github.com/strangesast/fwlib/blob/master/examples/c-minimal/main.c))
```
uint32_t cnc_ids[4];
...
cnc_rdcncid(libh, (unsigned long *)cnc_ids)
...

```

[Here is an example](https://gist.github.com/strangesast/5d576b12e76e62f9d651485c86823b5e) reading the spindle speed that should work on a 64bit platform.  The key thing is creating a struct with the "correct" field sizes and casting to the library's "wrong" field sizes.

**Comment by qmzeng** [comment]
Thanks, this is really helpful
