### ISSUE TITLE
Compile for aarch64

### ISSUE THREAD

**Issue by mauringo** [strangesast/fwlib#11]
Hi, 

Sorry to bother, i go directly to my question:
Is there a way to compile and run the examples on AARC64?

**Comment by strangesast** [comment]
No problem at all.  #3 covers compiling and running an example on aarch64.  It's basically just
```
arm-linux-gnueabihf-gcc your_file.c -L./ -Wl,-rpath=./ -lpthread -lfwlib32 -o your_binary
```
