### ISSUE TITLE
Hello, will you support macos？

### ISSUE THREAD

**Issue by Sunnnner** [strangesast/fwlib#15]
get error 
d: warning: ignoring file /usr/local/lib/libfwlib.so, building for macOS-x86_64 but attempting to link with file built for unknown-unsupported file format ( 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 )
 ld: warning: object file (/Users/knd/Desktop/20230606/pro1/src-tauri/target/debug/deps/libobjc_exception-236369846b337e66.rlib(exception.o)) was built for newer macOS version (12.0) than being linked (10.13)
          ld: warning: object file (/Users/knd/Desktop/20230606/pro1/src-tauri/target/debug/deps/libtao-2d885f6670b54971.rlib(carbon_hotkey_binding.o)) was built for newer macOS version (12.0) than being linked (10.13)
          Undefined symbols for architecture x86_64:
            "_cnc_allclibhndl3", referenced from:
                productLineControl::send_file_to_fanuc_cnc::_$u7b$$u7b$closure$u7d$$u7d$::he83a4abb63bc6a11 in productLineControl-6ea42e8d455301db.2lidcfi07cay98pl.rcgu.o
            "_cnc_download3", referenced from:
                productLineControl::dw_file::h97a2371f2908b212 in productLineControl-6ea42e8d455301db.4np8v3r30bw0rxwz.rcgu.o
            "_cnc_dwnend3", referenced from:
                productLineControl::dw_file::h97a2371f2908b212 in productLineControl-6ea42e8d455301db.4np8v3r30bw0rxwz.rcgu.o
            "_cnc_dwnstart3", referenced from:
                productLineControl::dw_file::h97a2371f2908b212 in productLineControl-6ea42e8d455301db.4np8v3r30bw0rxwz.rcgu.o
            "_cnc_freelibhndl", referenced from:
                productLineControl::send_file_to_fanuc_cnc::_$u7b$$u7b$closure$u7d$$u7d$::he83a4abb63bc6a11 in productLineControl-6ea42e8d455301db.2lidcfi07cay98pl.rcgu.o
          ld: symbol(s) not found for architecture x86_64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by strangesast** [comment]
the shared library files (.so & .dll) are compiled for Linux and MS Windows.  you may be able to compile and run code that uses these libraries on MacOS with Docker or a VM but there's no easy way to use these library files directly on that platform
