### ISSUE TITLE
What function should the set S be obtained by

### ISSUE THREAD

**Issue by miaokela** [strangesast/fwlib#19]
<img width="382" alt="image" src="https://github.com/strangesast/fwlib/assets/30903265/abda714a-b296-4fac-93ff-30b20861e005">
I have a question, what function is used to get this set value

**Comment by strangesast** [comment]
If that is spindle speed you may have luck with [https://www.inventcom.net/fanuc-focas-library/position/cnc_rdspeed](cnc_rdspeed), [https://www.inventcom.net/fanuc-focas-library/position/cnc_acts](cnc_acts), or [https://www.inventcom.net/fanuc-focas-library/position/cnc_rddynamic2](cnc_rddynamic2).


Or, take a look at this [https://github.com/strangesast/fwlib/blob/spindle-speed-example/examples/c-minimal/main.c](thisexample).

**Comment by miaokela** [comment]
thank you.
