### ISSUE TITLE
Got an error on Ubuntu 16 64bit

### ISSUE THREAD

**Issue by sharekte** [strangesast/fwlib#2]
Hi
I used libfwlib32-linux-x64.so.1.0.5 by Python directly but got the below error from gdb
**0x00007ffff6177f22 in cnc_allclibhndl4 () from /usr/local/lib/libfwlib32.so.1**
I call cnc_allclibhndl3 function in python code only
`result = focas.cnc_allclibhndl3(c_char_p(self.ip), c_ushort(self.port), c_long(self.timeout),addressof(self.handler))`
Pls help to check
Thanks

**Comment by strangesast** [comment]
Hi
Check out the [ctypes example](https://github.com/strangesast/fwlib/blob/master/examples/ctypes/main.py) I just pushed.

[The part you're concerned with](https://github.com/strangesast/fwlib/blob/master/examples/ctypes/main.py#L20-L31):
```python
libh = ctypes.c_ushort(0)  
ret = focas.cnc_allclibhndl3(
    b"127.0.0.1",
    8193,
    10,
    ctypes.byref(libh),
)
```

**Comment by sharekte** [comment]
Hi strangesast
My code works now.
And C parameter such as **unsigned short**,**long int** doesn't need **ctypes** to convert directly,correct?
Thanks

**Comment by strangesast** [comment]
yeah from [the docs](https://docs.python.org/3/library/ctypes.html) it looks like `None`, `int`, `bytes`, and `str` are converted to corresponding ctypes but you can override those by adding an `_as_parameter_` attr to an argument or add the `argtypes` or `restype` attrs to the wrapped function

the cnc_allclibhndl3 seems to require char* (not wchar*) so it fails when using `str` as the first argument, for example
