### ISSUE TITLE
Question about aarch64 support

### ISSUE THREAD

**Issue by applea9** [strangesast/fwlib#3]
I see you have aarch64 related branch, is the focas library fully supported on aarch64 device, like raspberry pi 4?

**Comment by strangesast** [comment]
yes but you need to install a few libraries to run and a few more to compile code that uses armv7/armhf shared libraries.  on aarch64 debian:
```
dpkg --add-architecture armhf
apt-get update
apt-get install -y libc6-dev:armhf gcc-arm-linux-gnueabihf
arm-linux-gnueabihf-gcc your_file.c -L./ -Wl,-rpath=./ -lpthread -lfwlib32 -o your_binary
./your_binary
```
if you have docker, the file in the root of this repository creates a working environment for aarch64 (and armhf, x86, x86_64) that you can build from.  you can also step through this file to see what's required if you wanted to do it manually.

to summarize this works fine on pi 4 (with pi os 32 and 64 bit) and older v7 or armhf pi's (not the pi 1 or pi 2, I believe)

**Comment by applea9** [comment]
Thanks a lot.

**Comment by liuxgo** [comment]
@strangesast Hi, how to compile golang code on aarch64 debian?
