### ISSUE TITLE
Bind the socket to an interface 

### ISSUE THREAD

**Issue by cgtygzgn** [strangesast/fwlib#4]
is it possible to use library functions to bind the socket that the focas creates to a different interface ?

**Comment by strangesast** [comment]
No, not that I'm aware of.

It appears that setsockopt is used internally by the library (as indicated by https://www.inventcom.net/fanuc-focas-library/general/errcode, which is retrieved by https://www.inventcom.net/fanuc-focas-library/misc/cnc_getdtailerr).  I think you may be able to restrict to a specific interface based on remote IP with an iptables rule.

Fanuc and several vendors (e.g. inventcom) are usually pretty responsive and could give you a more thorough and accurate answer.  My understanding is that Linux support has been discontinued as of a few years ago if that's your target platform.
