### ISSUE TITLE
Perform "cmake .." fail in "examples/c/build"

### ISSUE THREAD

**Issue by jackie-mantou** [strangesast/fwlib#5]
Hi, here comes a question.

Like the title, I perform command `cmake ..` failed  in directory  `examples/c/build` and get the following error message:
```
CMake Error at test/CMakeLists.txt:3 (add_subdirectory):
  The source directory

    /home/guosj/Documents/xuelangOpenSourceProject/fwlib/examples/c/extern/googletest

  does not contain a CMakeLists.txt file.


-- Configuring incomplete, errors occurred!
See also "/home/guosj/Documents/xuelangOpenSourceProject/fwlib/examples/c/build/CMakeFiles/CMakeOutput.log".
```

So, how to fix it?

**Comment by strangesast** [comment]
Hi.  You're missing git submodules used by this example.  Run `git submodule update --init --recursive` to fetch them and it should build correctly.

I've updated the [README](https://github.com/strangesast/fwlib/blob/master/examples/c/README.md) with a note about this requirement.

**Comment by strangesast** [comment]
Also, check out the [c-minimal](https://github.com/strangesast/fwlib/tree/master/examples/c-minimal) example, which may be easier to get started with.
