### ISSUE TITLE
skipping incompatible fwlib32.lib

### ISSUE THREAD

**Issue by forcmti** [strangesast/fwlib#6]
I am trying to run c-minimal example and i am getting this error.
I am running this on windows10

To Run this
`gcc -L./ -Wl,-rpath . examples/c-minimal/main.c -lfwlib32 -lm -lpthread -o fanuc_minimal`

Output
`skipping incompatible .//fwlib32.lib when searching for -lfwlib32`
`skipping incompatible .//fwlib32.dll when searching for -lfwlib32`
`skipping incompatible .//fwlib32.lib when searching for -lfwlib32`
`skipping incompatible .//fwlib32.dll when searching for -lfwlib32`
`skipping incompatible ./\fwlib32.lib when searching for -lfwlib32`
`skipping incompatible cannot find -lfwlib32`

Is this related to your .lib or its error on my part because of my configuration

**Comment by bolduz** [comment]
Did you try to use the 64 bit version?

My build commands on Windows are (I am using Code::Blocks 20.03 with the GNU GCC Compiler):

```
gcc.exe -Wall -Wextra -Wall -m64 -g  -c C:\Users\Username\Documents\Projects\test--codeblocks-c--fanuc-focas\main.c -o obj\Debug\main.o
gcc.exe -Llib -o bin\Debug\test--codeblocks-c--fanuc-focas.exe obj\Debug\main.o  -m64 -lfwlib64  
Output file is bin\Debug\test--codeblocks-c--fanuc-focas.exe with size 94.14 KB
```

**Comment by strangesast** [comment]
I agree with @bolduz  that this looks like an architecture incompatibility.  With `gcc` on Linux, normally you would use `gcc -m32 ...` to compile with the 32-bit library.

I don't have a windows machine with `gcc` installed but if you have Visual Studio or Visual Studio tools (`cl.exe`), the build command looks like this:
```
cl.exe /Fe"fanuc_minimal.exe" .\examples\c-minimal\main.c /link .\Fwlib32.lib
```

If building with `gcc` on windows is a hard requirement, I can take another look at why this may not be working for you.

I've updated the [README](https://github.com/strangesast/fwlib/tree/master/examples/c-minimal#readme) with notes for building c-minimal on Windows

**Comment by forcmti** [comment]
Yes with Visual Studio I was able to Run the Code and it starts Working. Thanks for the Help

**Comment by lovedva** [comment]
you should use fwlib64.dll libraries on win10,i thinks might help https://github.com/wheeliar/FANUC_Focas_API/tree/main/Fwlib64
```
gcc main.c -o cppx64.dll -DBUILD_DLL -L. -lFwlib64  -shared 
```
