### ISSUE TITLE
Libs for armv7

### ISSUE THREAD

**Issue by SkaiBoa** [strangesast/fwlib#7]
Hi there,

I'm looking for the lib for 1.0.0 for armv7.

The lib libfwlib32-linux-armv7.so.1.0.5 works fine for me. But unfortunately functions that I need have been removed in this version.

Is there any way to get these libs: libfwlib32-linux-armv7.so.1.0.0 or libfwlib32-linux-armv7.so.1.0.1?

Many thanks in advance.

**Comment by strangesast** [comment]
Sorry, everything I have is in the repo.

Arm support was added later (before Linux was dropped entirely 🙁)  so there may not be a module for that version/platform.  The folks at [inventcom.net](https://www.inventcom.net/) are very responsive and may know whether it exists.  A Fanuc rep would also be able to get that info for you, too.

If your arm chip is capable enough you could use the x86 1.0.0 shared library and emulate x86 with qemu or something like [FEX](https://github.com/FEX-Emu/FEX ) or [box86](https://github.com/ptitSeb/box86).

If you have any luck please let me know.  Feel free to PR any modules you manage to find to this repository.

**Comment by strangesast** [comment]
[Here's a Dockerfile](https://gist.github.com/strangesast/970324077f0942627fc4b93462748e75) for running the x86 1.0.0 shared library with qemu.  Tested on linux/arm64 and aarch64 in a vm and on a raspberry pi 4.
