### ISSUE TITLE
Libs for mipsel linux

### ISSUE THREAD

**Issue by sazima** [strangesast/fwlib#8]
Hello, do you have any plans to compile the libs for  mipsel linux. Or tell me how to build it myself. Thanks

**Comment by strangesast** [comment]
It's probably impossible.  Fanuc haven't released libraries compiled for MIPS or MIPS linux.  The easiest way to run this library on unsupported platforms is through an arm/x86 emulator but I'm pretty sure that's not available for MIPS.

You may be able to sniff the socket traffic or use a library that has reverse-engineered the protocol depending on the level of complexity of your use case.
