### ISSUE TITLE
Can the library support the reading of pmc data?

### ISSUE THREAD

**Issue by java-orange** [strangesast/fwlib#9]
Can the library support the reading of pmc data?

**Comment by strangesast** [comment]
I do not have experience with reading/writing Fanuc PMC data with this library but there are the functions [pmc_wrpmcrng](https://www.inventcom.net/fanuc-focas-library/pmc/pmc_wrpmcrng), [pmc_rdpmcrng](https://www.inventcom.net/fanuc-focas-library/Pmc/pmc_rdpmcrng), and [pmc_rdpmcinfo](https://www.inventcom.net/fanuc-focas-library/Pmc/pmc_rdpmcinfo) that may be suitable for your use case.

**Comment by java-orange** [comment]
oh, thank you very match, i will test for this and provide the result
